version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/shadowcal
    docker:
      - image: circleci/ruby:2.3.5-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.5
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
            - v1-gems-

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create db:schema:load --trace

      # Run rspec in parallel
      - run: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
