postgres:
  image: postgres:9.5
  environment:
    POSTGRES_USER: shadowcal
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - shadowcal-postgres:/var/lib/postgresql/data

shadowcal:
  build: .
  links:
    - postgres
  volumes:
    - .:/shadowcal
  ports:
    - '8000:8000'
  env_file:
    - .shadowcal.env