version: '3'

volumes:
  app:

services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ".:${APP_PATH}"

  app:
    build: 
      context: .
      args:
        - 'PORT=80'
        - 'RACK_ENV=$RACK_ENV'
        - 'APP_PATH=$APP_PATH'
    links:
      - postgres
    volumes:
      - ".:${APP_PATH}"
    ports:
      - "80:80"
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p $PORT -e $RACK_ENV -b 0.0.0.0"