default: &default
  adapter: postgresql 
  encoding: unicode 
  pool: 5 
  timeout: 5000 
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  host: <%= ENV["RDS_HOSTNAME"] %>
  port: <%= ENV["RDS_PORT"] %>

production:
  <<: *default
  database: <%= ENV["RDS_DB_NAME"] %>

development:
  <<: *default
  database: shadowcal_development

test:
  <<: *default
  database: shadowcal_test