default: &default
  adapter: postgresql 
  encoding: unicode 
  pool: 5 
  timeout: 5000 
  username: postgres 
  host: postgres
  port: 5432

production:
  <<: *default
  database: shadowcal_production

development:
  <<: *default
  database: shadowcal_development

test:
  <<: *default
  database: shadowcal_test